--------------------------------------------------------
--  File created - Tuesday-April-16-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ADMINSEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MMS"."ADMINSEQ"  MINVALUE 101 MAXVALUE 999 INCREMENT BY 1 START WITH 141 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BRANCHADMINSEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MMS"."BRANCHADMINSEQ"  MINVALUE 11 MAXVALUE 999 INCREMENT BY 1 START WITH 91 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence HIBERNATE_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "MMS"."HIBERNATE_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MEDICINEREQUESTID
--------------------------------------------------------

   CREATE SEQUENCE  "MMS"."MEDICINEREQUESTID"  MINVALUE 11 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 93 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MEDICINESEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MMS"."MEDICINESEQ"  MINVALUE 1 MAXVALUE 100 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ADMIN
--------------------------------------------------------

  CREATE TABLE "MMS"."ADMIN" 
   (	"ADMINID" VARCHAR2(10 BYTE) DEFAULT 1, 
	"FIRST_NAME" VARCHAR2(50 BYTE), 
	"LAST_NAME" VARCHAR2(50 BYTE), 
	"AGE" NUMBER(2,0), 
	"GENDER" VARCHAR2(20 BYTE), 
	"DOB" VARCHAR2(10 BYTE), 
	"CONTACT_NUMBER" NUMBER(10,0), 
	"ALT_CONTACT_NUMBER" NUMBER(10,0), 
	"EMAIL_ID" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BRANCH_ADMIN
--------------------------------------------------------

  CREATE TABLE "MMS"."BRANCH_ADMIN" 
   (	"BRANCH_ADMIN_ID" VARCHAR2(100 BYTE), 
	"FIRST_NAME" VARCHAR2(50 BYTE), 
	"LAST_NAME" VARCHAR2(50 BYTE), 
	"AGE" NUMBER(2,0), 
	"GENDER" VARCHAR2(20 BYTE), 
	"DOB" VARCHAR2(10 BYTE), 
	"CONTACT_NUMBER" VARCHAR2(10 BYTE), 
	"ALT_CONTACT_NUMBER" VARCHAR2(10 BYTE), 
	"EMAIL_ID" VARCHAR2(50 BYTE), 
	"BRANCH_NAME" VARCHAR2(50 BYTE), 
	"ADDRESS_LINE_1" VARCHAR2(100 BYTE), 
	"ADDRESS_LINE_2" VARCHAR2(100 BYTE), 
	"CITY" VARCHAR2(50 BYTE), 
	"STATE" VARCHAR2(50 BYTE), 
	"ZIP_CODE" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BRANCH_ADMIN_REQUEST
--------------------------------------------------------

  CREATE TABLE "MMS"."BRANCH_ADMIN_REQUEST" 
   (	"REQUEST_ID" NUMBER(8,0), 
	"BRANCH_ADMIN_ID" VARCHAR2(10 BYTE), 
	"REQUEST_DATE" VARCHAR2(200 BYTE), 
	"MEDICINE_ID_1" NUMBER DEFAULT 0, 
	"QUANTITY1" NUMBER(3,0) DEFAULT 0, 
	"MEDICINE_ID_2" NUMBER DEFAULT 0, 
	"QUANTITY2" NUMBER(3,0) DEFAULT 0, 
	"MEDICINE_ID_3" NUMBER DEFAULT 0, 
	"QUANTITY3" NUMBER(3,0) DEFAULT 0, 
	"MEDICINE_ID_4" NUMBER DEFAULT 0, 
	"QUANTITY4" NUMBER(3,0) DEFAULT 0, 
	"MEDICINE_ID_5" NUMBER DEFAULT 0, 
	"QUANTITY5" NUMBER(3,0) DEFAULT 0, 
	"OTHER_INFO" VARCHAR2(200 BYTE), 
	"ADMIN_PROCESS_DATE" VARCHAR2(20 BYTE), 
	"ADMIN_RESPONSE" VARCHAR2(1 BYTE) DEFAULT 'P', 
	"ADMIN_REMARKS" VARCHAR2(300 BYTE), 
	"REQUES_DATE" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEDICINE
--------------------------------------------------------

  CREATE TABLE "MMS"."MEDICINE" 
   (	"MEDICINE_ID" NUMBER(8,0), 
	"MEDICINE_DESCRIPTION" VARCHAR2(200 BYTE), 
	"CURE_FOR" VARCHAR2(100 BYTE), 
	"MANUFACTURING_COMPANY" VARCHAR2(50 BYTE), 
	"DOSAGE" NUMBER(3,0), 
	"PRESCRIBED_FOR" VARCHAR2(1 BYTE), 
	"QUANTITY" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REQUESTRESPONSETRIGGERTABLE
--------------------------------------------------------

  CREATE TABLE "MMS"."REQUESTRESPONSETRIGGERTABLE" 
   (	"PENDING" NUMBER DEFAULT 0, 
	"APPROVED" NUMBER DEFAULT 0, 
	"SRNO" VARCHAR2(20 BYTE) DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into MMS.ADMIN
SET DEFINE OFF;
Insert into MMS.ADMIN (ADMINID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,PASSWORD) values ('1','Mark','Henry',20,'M','21/11/1996',9632587410,null,'abc@xyz.com','abc');
Insert into MMS.ADMIN (ADMINID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,PASSWORD) values ('2','xtz','singh',48,'Male','12/5/1989',7894561233,7410258963,'ps@ers','tree');
Insert into MMS.ADMIN (ADMINID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,PASSWORD) values ('4','vdf','dfdfs',12,'Male','12/2/1996',1234567890,1234567900,'dfgg','dffse');
Insert into MMS.ADMIN (ADMINID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,PASSWORD) values ('3','all','is well',12,'Male','12/34/1212',2124344334,2133433432,'xcvfgv','wsdweqd');
Insert into MMS.ADMIN (ADMINID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,PASSWORD) values ('admin1','sdsds','sdsds',22,'Male','11/02/2018',23232,2323,'ssdsds','sdsdsd');
Insert into MMS.ADMIN (ADMINID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,PASSWORD) values ('admin25','ddd','ddd',34,'Female','11/02/2018',7777777,7777777,'dddddd','333');
Insert into MMS.ADMIN (ADMINID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,PASSWORD) values ('admin26','fdf','dfdf',23,'Female','11/02/2018',2222,2222,'ssss','2222');
Insert into MMS.ADMIN (ADMINID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,PASSWORD) values ('admin27','dvds','vsdvc',21,'Male','1/1/1234',4563456,45345,'gfs','sgsfd');
Insert into MMS.ADMIN (ADMINID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,PASSWORD) values ('admin21','dfd','dscs',12,'Male','12/12/1234',5656,4544,'dfg','dsg');
Insert into MMS.ADMIN (ADMINID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,PASSWORD) values ('admin42','akash','bansal',24,'Male','12/12/1995',1232346534,23423423,'gfsdg','gfdf');
Insert into MMS.ADMIN (ADMINID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,PASSWORD) values ('admin22','trt','erter',12,'Male','12/12/1234',32434,3434,'dfdsf','dfafdf');
Insert into MMS.ADMIN (ADMINID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,PASSWORD) values ('admin45','sarth','asdas',35,'Male','3/3/1234',45345,565645,'gh','ggfbdf');
Insert into MMS.ADMIN (ADMINID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,PASSWORD) values ('admin46','ds','df',22,'Female','1/1/1221',123123,2323213,'dfwdfv','dfdfdfsd');
Insert into MMS.ADMIN (ADMINID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,PASSWORD) values ('admin47','sar','vhj',76,'Male','32/21/1223',7678968979,null,'gyvhjy','hvg');
Insert into MMS.ADMIN (ADMINID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,PASSWORD) values ('admin50','Nitin','Verma',21,'Male','2019-03-17',1298992121,2345345634,'nitin@gmail.com','abcasdfgfv');
Insert into MMS.ADMIN (ADMINID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,PASSWORD) values ('admin61','payush','bathla',21,'Male','1996-08-20',9872860681,7009184485,'payush22@gmail.com','gfgy');
Insert into MMS.ADMIN (ADMINID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,PASSWORD) values ('admin62','ert','gfrf',34,'Female','2019-04-01',4356435555,5435455454,'gfd@gmail.com','hgfhfhghgf');
Insert into MMS.ADMIN (ADMINID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,PASSWORD) values ('admin102','xbvdfbv','sdfvgsd',29,'NONE','1990-06-20',4563453123,1241341234,'dsf@gmail.com','4353453453');
Insert into MMS.ADMIN (ADMINID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,PASSWORD) values ('admin82','rgtreg','fgef',45,'Male','2019-04-08',4352345234,23423,'dfssdf@gmail.com','56565656');
Insert into MMS.ADMIN (ADMINID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,PASSWORD) values ('admin83','yahoo','Google',0,'Male','12/5/7852',785241630,147852369,'google@yahoo.com','508417963');
Insert into MMS.ADMIN (ADMINID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,PASSWORD) values ('admin96','henry','NITIN',0,'Male','45/7/789',7854120369,7410258963,'henry@gmail.com','789456@GT');
Insert into MMS.ADMIN (ADMINID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,PASSWORD) values ('admin97','TREE','mango',0,'Male','45/4/8',7410258963,null,'ui@tr.com','7845');
Insert into MMS.ADMIN (ADMINID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,PASSWORD) values ('admin101','ghgdgr','fdgdfgdfg',22,'NONE','1997-06-17',6546456456,5645645665,'vggfdf@gmail.com','4534534545');
Insert into MMS.ADMIN (ADMINID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,PASSWORD) values ('admin103','awdr','asd',25,'male','1994-02-08',3333333333,5435435555,'sds@gmail.com','saasasssas');
Insert into MMS.ADMIN (ADMINID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,PASSWORD) values ('admin104','adminFname','adminLastName',0,'M','21/11/7895',2013456789,4567891230,'adminEmailId@gmial.com','50822010');
Insert into MMS.ADMIN (ADMINID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,PASSWORD) values ('admin105','adminFname','adminLastName',0,'M','21/11/7895',9013456789,4567891230,'mailId@gmial.com','50822010');
Insert into MMS.ADMIN (ADMINID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,PASSWORD) values ('admin106','ronny','Malik',21,'Female','1998-02-03',7410326598,null,'yahoo@google.com','741258@os');
Insert into MMS.ADMIN (ADMINID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,PASSWORD) values ('admin107','Bhushan','Mittal',31,'male','1988-07-14',9192231121,null,'bhushan@gmail.com','12345');
Insert into MMS.ADMIN (ADMINID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,PASSWORD) values ('admin108','grapes','angoor',4,'Male','15/5/1975',7410258966,null,'grapes@angoor.com','8520');
Insert into MMS.ADMIN (ADMINID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,PASSWORD) values ('admin121','tuty','tyu',26,'male','1993-06-15',5675675675,7567567756,'a@gmail.com','dfgfr');
Insert into MMS.ADMIN (ADMINID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,PASSWORD) values ('admin122','sdf','sdf',52,'male','1967-02-14',5452345234,3453443434,'ff@gmail.com','gfdfg');
Insert into MMS.ADMIN (ADMINID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,PASSWORD) values ('admin123','sdf','sdf',52,'male','1967-02-14',5452345255,3453443434,'ff11@gmail.com','gfdfg');
Insert into MMS.ADMIN (ADMINID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,PASSWORD) values ('admin124','sdf','sdf',52,'male','1967-02-14',5452345257,3453443434,'ff111@gmail.com','gfdfg');
Insert into MMS.ADMIN (ADMINID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,PASSWORD) values ('admin125','balak','nath',0,'male','1992-03-03',9878545464,4564564564,'khjkh@mnjkh.com','balak');
Insert into MMS.ADMIN (ADMINID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,PASSWORD) values ('admin126','elephant','oro',0,'male','1996-11-05',3515156155,null,'joker@dree.com','123456Wpe');
Insert into MMS.ADMIN (ADMINID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,PASSWORD) values ('admin127','Abhi','Sharma',0,'male','1998-05-18',2156145645,null,'sgf@gmail.com','thcgfh');
REM INSERTING into MMS.BRANCH_ADMIN
SET DEFINE OFF;
Insert into MMS.BRANCH_ADMIN (BRANCH_ADMIN_ID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,BRANCH_NAME,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,STATE,ZIP_CODE) values ('1','hbghj','hjghj',25,'male','1994-02-08','9638527410','5456464646','abjhugh','hghjg','jhjkh','huh',' Kishtwar ','Jammu & Kashmir',54564);
Insert into MMS.BRANCH_ADMIN (BRANCH_ADMIN_ID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,BRANCH_NAME,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,STATE,ZIP_CODE) values ('2','nitinm','hjghj',65,'Male','12/5/4454','9638527410','5456464646','abjhugh','hghjg','jhjkh','huh','jkhu','hjkghug',54564);
Insert into MMS.BRANCH_ADMIN (BRANCH_ADMIN_ID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,BRANCH_NAME,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,STATE,ZIP_CODE) values ('3','payia','bathla',22,'Male','22/8/1996','9872860681','7009184485','payush22@gmail.com','cdc','abc','xyz','Abohar','punjab',152116);
Insert into MMS.BRANCH_ADMIN (BRANCH_ADMIN_ID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,BRANCH_NAME,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,STATE,ZIP_CODE) values ('branch29','nitin52','verma',25,'male','1994-01-04','1212232313','1212121212','balak1@gmail.com','dermatology','navy nagar','colaba','mumbai','mumbai',40005);
Insert into MMS.BRANCH_ADMIN (BRANCH_ADMIN_ID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,BRANCH_NAME,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,STATE,ZIP_CODE) values ('branch30','nitin','verma',41,'Male','9/11/1999','1231231234','1231232112','nitin@gmail.com','ENT','navy nagar','colaba','mumba','maharashtra',400005);
Insert into MMS.BRANCH_ADMIN (BRANCH_ADMIN_ID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,BRANCH_NAME,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,STATE,ZIP_CODE) values ('branch43','sadas','dasda',32,'Male','1/1/1234','34324','4324','dfdf','dfssd','fsdf','fsdf','dsf','fsdaf',23213);
Insert into MMS.BRANCH_ADMIN (BRANCH_ADMIN_ID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,BRANCH_NAME,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,STATE,ZIP_CODE) values ('branch11','aqw','sdwsdq',21,'Female','1/1/2312','45765676','5654656','dfsgdfg','gfdsg','gdsfg','fdgdf','gffdsg','gfsdg',43534);
Insert into MMS.BRANCH_ADMIN (BRANCH_ADMIN_ID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,BRANCH_NAME,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,STATE,ZIP_CODE) values ('branch12','rgf','gsdgf',45,'Female','2019-04-09','7876856456','8877756564','nitin@gmail.com','ghgfgf','ghhgfh','gfhgfh','gfhgfh','hgfh',675);
Insert into MMS.BRANCH_ADMIN (BRANCH_ADMIN_ID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,BRANCH_NAME,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,STATE,ZIP_CODE) values ('branch17','bvdfg','greg',34,'male','2019-04-16','3425545676','4545455645','a@gmail.com','gsdfgd','gfsdfg','dgdfg','dgdfg','dfgdf',566566);
Insert into MMS.BRANCH_ADMIN (BRANCH_ADMIN_ID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,BRANCH_NAME,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,STATE,ZIP_CODE) values ('branch45','zscsd','csdc',21,'Male','142442452','4534545364','3453454365','gdfg','gfbh','gfhgf','ghfbhgf','ghgfbh','gfhbgf',123123);
Insert into MMS.BRANCH_ADMIN (BRANCH_ADMIN_ID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,BRANCH_NAME,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,STATE,ZIP_CODE) values ('branch51','Harsh','Ranjan',22,'Male','2019-04-09','1334453454','5345666565','hr@gmail.com','vgfbfb','ghtrgtrsghtr','ghbgrdhgdhgh','bgrsd','gfrbf',45365);
Insert into MMS.BRANCH_ADMIN (BRANCH_ADMIN_ID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,BRANCH_NAME,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,STATE,ZIP_CODE) values ('branch56','thre','fsdakj',78,'Male','87/52/7894','7899555765',null,'ps@gmaiol.com;','greeem','yellow','blue','tree','forest',741852);
Insert into MMS.BRANCH_ADMIN (BRANCH_ADMIN_ID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,BRANCH_NAME,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,STATE,ZIP_CODE) values ('branch57','af','dsf',45,'Male','7/8/52','4561237890',null,'klahdlda','sdma;','masf;','CM,SD;','SDVM','FAM',456132);
Insert into MMS.BRANCH_ADMIN (BRANCH_ADMIN_ID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,BRANCH_NAME,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,STATE,ZIP_CODE) values ('branch71','asdg','gfr1',45,'Male','45/8/96','4561237800','7845452120','ps@gmail.oc','45','45adas','d4a5','fds','ad',456123);
Insert into MMS.BRANCH_ADMIN (BRANCH_ADMIN_ID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,BRANCH_NAME,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,STATE,ZIP_CODE) values ('branch77','vfsdf','fsdfdsf',27,'male','1992-06-16','4554354353','345345345','frs@gmail.com','fwerf','sdfsd','fsdf','sdfsd','dsfsd',342123);
Insert into MMS.BRANCH_ADMIN (BRANCH_ADMIN_ID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,BRANCH_NAME,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,STATE,ZIP_CODE) values ('branch78','gdgh','gfdfg',35,'female','1984-01-09','9638527419','9638527410','balak@gmail.co','gfgdf','bgdfvg','dfbvgdfv','dfsvf','sdfgsdf',343423);
Insert into MMS.BRANCH_ADMIN (BRANCH_ADMIN_ID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,BRANCH_NAME,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,STATE,ZIP_CODE) values ('branch79','trytr','yh',24,'female','1995-01-02','6756745454','756756','gfh@gmail.com','gfh','gfh','fgh',' Walchandnagar ','Maharashtra',346345);
Insert into MMS.BRANCH_ADMIN (BRANCH_ADMIN_ID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,BRANCH_NAME,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,STATE,ZIP_CODE) values ('branch80','fg','fdgf',24,'male','1995-01-02','5465565665','566','fdg@gmail.com','gfr','gfdg','gfd',' Kangra ','Himachal Pradesh',565645);
Insert into MMS.BRANCH_ADMIN (BRANCH_ADMIN_ID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,BRANCH_NAME,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,STATE,ZIP_CODE) values ('branch81','hhg','hghjg',59,'male','1960-02-02','9875545625','6464645645','kjkhjk@jhjkjh.bhj','ughg','ghhjghj','ghjghjg',' Balapur ','Maharashtra',545454);
Insert into MMS.BRANCH_ADMIN (BRANCH_ADMIN_ID,FIRST_NAME,LAST_NAME,AGE,GENDER,DOB,CONTACT_NUMBER,ALT_CONTACT_NUMBER,EMAIL_ID,BRANCH_NAME,ADDRESS_LINE_1,ADDRESS_LINE_2,CITY,STATE,ZIP_CODE) values ('branch82','gfd','fgd',19,'male','2000-01-30','4548646486','5464864646','kjhjkh@kjklhj.com','hjuhuihuh','jhuhuhh','uigyhghyug',' Kalpeni Island ','Lakshadweep',548456);
REM INSERTING into MMS.BRANCH_ADMIN_REQUEST
SET DEFINE OFF;
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (34,'1','545',1,0,1,0,1,0,1,0,1,0,null,null,'A',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (32,'1','54',1,0,1,0,1,0,1,0,1,0,null,null,'A',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (33,'1','4486',1,0,1,0,1,0,1,0,1,0,null,null,'A',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (35,'1','545',1,0,1,0,1,0,1,0,1,0,null,null,'A',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (38,'branch30','Wed Apr 03 2019 15:23:13 GMT+0530 (India Standard Time)',3,453,1,0,1,0,1,0,1,0,null,null,'A',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (39,'branch30','Wed Apr 03 2019 15:23:13 GMT+0530 (India Standard Time)',3,453,1,0,1,0,1,0,1,0,null,null,'A',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (40,'branch30','Wed Apr 03 2019 16:29:01 GMT+0530 (India Standard Time)',5,45,1,0,1,0,1,0,1,0,null,null,'A','approved',null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (41,'branch30','Wed Apr 03 2019 16:29:01 GMT+0530 (India Standard Time)',5,45,1,0,1,0,1,0,1,0,null,null,'A',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (42,'branch30','Wed Apr 03 2019 16:29:01 GMT+0530 (India Standard Time)',5,45,1,0,1,0,1,0,1,0,null,null,'A',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (44,'branch51','2019-04-04',5,12,0,0,0,0,0,0,0,0,'fcvfecve',null,'A',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (47,'1','2019-04-01',4,12,0,0,0,0,0,0,0,0,null,null,'A',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (48,'1','04/05/2019',33,23,0,0,0,0,0,0,0,0,null,null,'A',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (49,'branch12','04/05/2019',35,564,36,645,38,585,39,65,0,0,'bill',null,'R',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (50,'branch12','04/05/2019',35,564,36,645,38,585,39,65,0,0,'bill',null,'R',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (51,'branch12','04/05/2019',35,564,36,645,38,585,39,65,0,0,'bill',null,'R',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (52,'branch12','04/05/2019',35,564,36,645,38,585,39,65,0,0,'bill',null,'R',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (53,'branch12','04/05/2019',35,564,36,645,38,585,39,65,0,0,'bill',null,'R',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (54,'3','Fri Apr 05 2019 11:43:09 GMT+0530 (India Standard Time)',35,78,37,0,0,0,0,0,0,0,null,null,'A',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (55,'3','Fri Apr 05 2019 11:43:09 GMT+0530 (India Standard Time)',35,78,37,0,0,0,0,0,0,0,null,null,'A',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (56,'3','Fri Apr 05 2019 11:43:09 GMT+0530 (India Standard Time)',35,78,37,0,0,0,0,0,0,0,null,null,'A',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (57,'branch11','04/05/2019',37,45,35,0,35,0,35,0,35,0,'sdjghsi',null,'A',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (58,'1','Mon Apr 08 2019 10:18:37 GMT+0530 (India Standard Time)',36,0,35,0,35,0,35,0,35,0,null,null,'A',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (59,'1','04/08/2019',35,13,35,0,35,0,35,0,35,0,null,null,'A',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (60,'2','Mon Apr 08 2019 15:03:55 GMT+0530 (India Standard Time)',37,11,35,0,35,0,35,0,35,0,null,null,'A',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (61,'branch17','04/08/2019',35,56,35,0,35,0,35,0,35,0,null,null,'A',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (62,'branch11','04/10/2019',35,12,35,0,35,0,35,0,35,0,null,null,'A',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (63,'branch11','04/10/2019',35,12,35,0,35,0,35,0,35,0,null,null,'A',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (64,'branch11','04/10/2019',35,12,35,0,35,0,35,0,35,0,null,null,'R',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (71,'1','04/11/2019',38,768,35,0,35,0,35,0,61,0,null,null,'A',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (74,'1','04/12/2019',35,89,36,12,35,0,35,0,35,0,null,null,'A',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (76,'1','04/12/2019',35,21,35,0,35,0,35,0,35,0,null,null,'A','approved',null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (77,'branch11','Fri Apr 12 2019 17:20:08 GMT+0530 (India Standard Time)',63,475,36,45,35,4,37,11,62,5,'JMD',null,'R',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (78,'branch12','04/15/2019',35,55,50,57,35,0,35,0,35,0,'dfyhgfjgfj',null,'A',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (79,'1','04/15/2019',35,545,35,0,35,0,35,0,35,0,'fdhf',null,'A',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (80,'1','04/15/2019',35,545,35,0,35,0,35,0,35,0,'fdhf',null,'R',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (81,'1','04/15/2019',35,545,35,0,35,0,35,0,35,0,'fdhf',null,'R',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (82,'1','04/15/2019',35,545,35,0,35,0,35,0,35,0,'fdhf',null,'A',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (83,'1','04/15/2019',35,545,35,0,35,0,35,0,35,0,'kjkl',null,'A',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (84,'1','04/15/2019',35,545,35,0,35,0,35,0,35,0,'kjkl',null,'A',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (85,'1','04/15/2019',35,545,35,0,35,0,35,0,35,0,'kjkl',null,'A',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (86,'1','04/15/2019',35,545,35,0,35,0,35,0,35,0,'kjkl',null,'R',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (87,'1','04/15/2019',35,5,35,0,35,0,35,0,35,0,null,null,'A',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (88,'1','04/15/2019',35,90,35,0,35,0,35,0,35,0,null,null,'R',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (89,'1','04/15/2019',35,55,35,0,35,0,35,0,35,0,null,null,'P',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (90,'1','04/15/2019',35,56,35,0,35,0,35,0,35,0,null,null,'P',null,null);
Insert into MMS.BRANCH_ADMIN_REQUEST (REQUEST_ID,BRANCH_ADMIN_ID,REQUEST_DATE,MEDICINE_ID_1,QUANTITY1,MEDICINE_ID_2,QUANTITY2,MEDICINE_ID_3,QUANTITY3,MEDICINE_ID_4,QUANTITY4,MEDICINE_ID_5,QUANTITY5,OTHER_INFO,ADMIN_PROCESS_DATE,ADMIN_RESPONSE,ADMIN_REMARKS,REQUES_DATE) values (92,'1','04/15/2019',35,455,35,0,35,0,35,0,35,0,null,null,'P',null,null);
REM INSERTING into MMS.MEDICINE
SET DEFINE OFF;
Insert into MMS.MEDICINE (MEDICINE_ID,MEDICINE_DESCRIPTION,CURE_FOR,MANUFACTURING_COMPANY,DOSAGE,PRESCRIBED_FOR,QUANTITY) values (35,'this is for mental heath','hgh','cipla',54,'A',45555);
Insert into MMS.MEDICINE (MEDICINE_ID,MEDICINE_DESCRIPTION,CURE_FOR,MANUFACTURING_COMPANY,DOSAGE,PRESCRIBED_FOR,QUANTITY) values (36,'this is for mental heath','hgh','cipla',54,'A',87);
Insert into MMS.MEDICINE (MEDICINE_ID,MEDICINE_DESCRIPTION,CURE_FOR,MANUFACTURING_COMPANY,DOSAGE,PRESCRIBED_FOR,QUANTITY) values (37,'this is for mental heath','hgh','cipla',123,'A',5600);
Insert into MMS.MEDICINE (MEDICINE_ID,MEDICINE_DESCRIPTION,CURE_FOR,MANUFACTURING_COMPANY,DOSAGE,PRESCRIBED_FOR,QUANTITY) values (38,'this is for mental heath','hgh','cipla',654,'C',7890);
Insert into MMS.MEDICINE (MEDICINE_ID,MEDICINE_DESCRIPTION,CURE_FOR,MANUFACTURING_COMPANY,DOSAGE,PRESCRIBED_FOR,QUANTITY) values (39,'this is for mental heath','hgh','cipla',0,'A',10);
Insert into MMS.MEDICINE (MEDICINE_ID,MEDICINE_DESCRIPTION,CURE_FOR,MANUFACTURING_COMPANY,DOSAGE,PRESCRIBED_FOR,QUANTITY) values (50,'gfffnhfh','sdf','sfset',45,'A',785);
Insert into MMS.MEDICINE (MEDICINE_ID,MEDICINE_DESCRIPTION,CURE_FOR,MANUFACTURING_COMPANY,DOSAGE,PRESCRIBED_FOR,QUANTITY) values (61,'sdsd','sdsds','sdsds',1,'A',1);
Insert into MMS.MEDICINE (MEDICINE_ID,MEDICINE_DESCRIPTION,CURE_FOR,MANUFACTURING_COMPANY,DOSAGE,PRESCRIBED_FOR,QUANTITY) values (62,'sdsd','sdsds','sdsds',1,'A',1);
Insert into MMS.MEDICINE (MEDICINE_ID,MEDICINE_DESCRIPTION,CURE_FOR,MANUFACTURING_COMPANY,DOSAGE,PRESCRIBED_FOR,QUANTITY) values (63,'sdsd','sdsds','sdsds',1,'A',855);
Insert into MMS.MEDICINE (MEDICINE_ID,MEDICINE_DESCRIPTION,CURE_FOR,MANUFACTURING_COMPANY,DOSAGE,PRESCRIBED_FOR,QUANTITY) values (64,'gfddf','gdfg','dsfsd',7,'A',67);
Insert into MMS.MEDICINE (MEDICINE_ID,MEDICINE_DESCRIPTION,CURE_FOR,MANUFACTURING_COMPANY,DOSAGE,PRESCRIBED_FOR,QUANTITY) values (65,'gfddf','gdfg','dsfsd',7,'A',67);
Insert into MMS.MEDICINE (MEDICINE_ID,MEDICINE_DESCRIPTION,CURE_FOR,MANUFACTURING_COMPANY,DOSAGE,PRESCRIBED_FOR,QUANTITY) values (66,'gfddf','gdfg','dsfsd',7,'A',67);
Insert into MMS.MEDICINE (MEDICINE_ID,MEDICINE_DESCRIPTION,CURE_FOR,MANUFACTURING_COMPANY,DOSAGE,PRESCRIBED_FOR,QUANTITY) values (67,'gfddf','gdfg','dsfsd',7,'A',67);
Insert into MMS.MEDICINE (MEDICINE_ID,MEDICINE_DESCRIPTION,CURE_FOR,MANUFACTURING_COMPANY,DOSAGE,PRESCRIBED_FOR,QUANTITY) values (68,'bghjg','hjhjg','gghfgh',78,'A',87);
Insert into MMS.MEDICINE (MEDICINE_ID,MEDICINE_DESCRIPTION,CURE_FOR,MANUFACTURING_COMPANY,DOSAGE,PRESCRIBED_FOR,QUANTITY) values (69,'bghjg','hjhjg','gghfgh',78,'A',87);
Insert into MMS.MEDICINE (MEDICINE_ID,MEDICINE_DESCRIPTION,CURE_FOR,MANUFACTURING_COMPANY,DOSAGE,PRESCRIBED_FOR,QUANTITY) values (70,'gfddf','gdfg','dsfsd',7,'A',67);
Insert into MMS.MEDICINE (MEDICINE_ID,MEDICINE_DESCRIPTION,CURE_FOR,MANUFACTURING_COMPANY,DOSAGE,PRESCRIBED_FOR,QUANTITY) values (71,'gfhgfr','gfhgf','ghgf',23,'A',34);
Insert into MMS.MEDICINE (MEDICINE_ID,MEDICINE_DESCRIPTION,CURE_FOR,MANUFACTURING_COMPANY,DOSAGE,PRESCRIBED_FOR,QUANTITY) values (72,'gfhgfr','gfhgf','ghgf',23,'A',34);
REM INSERTING into MMS.REQUESTRESPONSETRIGGERTABLE
SET DEFINE OFF;
Insert into MMS.REQUESTRESPONSETRIGGERTABLE (PENDING,APPROVED,SRNO) values (3,32,'1');
--------------------------------------------------------
--  DDL for Index BRANCH_ADMIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MMS"."BRANCH_ADMIN_PK" ON "MMS"."BRANCH_ADMIN" ("BRANCH_ADMIN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MEDICINE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MMS"."MEDICINE_PK" ON "MMS"."MEDICINE" ("MEDICINE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index REQUESTRESPONSETRIGGERTABL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MMS"."REQUESTRESPONSETRIGGERTABL_PK" ON "MMS"."REQUESTRESPONSETRIGGERTABLE" ("SRNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MMS"."TABLE1_PK" ON "MMS"."ADMIN" ("ADMINID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ADMIN
--------------------------------------------------------

  ALTER TABLE "MMS"."ADMIN" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ADMINID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MMS"."ADMIN" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "MMS"."ADMIN" MODIFY ("EMAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "MMS"."ADMIN" MODIFY ("CONTACT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "MMS"."ADMIN" MODIFY ("DOB" NOT NULL ENABLE);
  ALTER TABLE "MMS"."ADMIN" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "MMS"."ADMIN" MODIFY ("AGE" NOT NULL ENABLE);
  ALTER TABLE "MMS"."ADMIN" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "MMS"."ADMIN" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "MMS"."ADMIN" MODIFY ("ADMINID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BRANCH_ADMIN
--------------------------------------------------------

  ALTER TABLE "MMS"."BRANCH_ADMIN" MODIFY ("ZIP_CODE" NOT NULL ENABLE);
  ALTER TABLE "MMS"."BRANCH_ADMIN" MODIFY ("STATE" NOT NULL ENABLE);
  ALTER TABLE "MMS"."BRANCH_ADMIN" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "MMS"."BRANCH_ADMIN" MODIFY ("ADDRESS_LINE_1" NOT NULL ENABLE);
  ALTER TABLE "MMS"."BRANCH_ADMIN" MODIFY ("BRANCH_NAME" NOT NULL ENABLE);
  ALTER TABLE "MMS"."BRANCH_ADMIN" MODIFY ("EMAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "MMS"."BRANCH_ADMIN" MODIFY ("CONTACT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "MMS"."BRANCH_ADMIN" MODIFY ("DOB" NOT NULL ENABLE);
  ALTER TABLE "MMS"."BRANCH_ADMIN" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "MMS"."BRANCH_ADMIN" MODIFY ("AGE" NOT NULL ENABLE);
  ALTER TABLE "MMS"."BRANCH_ADMIN" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "MMS"."BRANCH_ADMIN" ADD CONSTRAINT "BRANCH_ADMIN_PK" PRIMARY KEY ("BRANCH_ADMIN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MMS"."BRANCH_ADMIN" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "MMS"."BRANCH_ADMIN" MODIFY ("BRANCH_ADMIN_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BRANCH_ADMIN_REQUEST
--------------------------------------------------------

  ALTER TABLE "MMS"."BRANCH_ADMIN_REQUEST" MODIFY ("QUANTITY1" NOT NULL ENABLE);
  ALTER TABLE "MMS"."BRANCH_ADMIN_REQUEST" MODIFY ("MEDICINE_ID_1" NOT NULL ENABLE);
  ALTER TABLE "MMS"."BRANCH_ADMIN_REQUEST" MODIFY ("REQUEST_DATE" NOT NULL ENABLE);
  ALTER TABLE "MMS"."BRANCH_ADMIN_REQUEST" MODIFY ("BRANCH_ADMIN_ID" NOT NULL ENABLE);
  ALTER TABLE "MMS"."BRANCH_ADMIN_REQUEST" MODIFY ("REQUEST_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEDICINE
--------------------------------------------------------

  ALTER TABLE "MMS"."MEDICINE" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "MMS"."MEDICINE" ADD CONSTRAINT "MEDICINE_PK" PRIMARY KEY ("MEDICINE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MMS"."MEDICINE" MODIFY ("PRESCRIBED_FOR" NOT NULL ENABLE);
  ALTER TABLE "MMS"."MEDICINE" MODIFY ("DOSAGE" NOT NULL ENABLE);
  ALTER TABLE "MMS"."MEDICINE" MODIFY ("MANUFACTURING_COMPANY" NOT NULL ENABLE);
  ALTER TABLE "MMS"."MEDICINE" MODIFY ("CURE_FOR" NOT NULL ENABLE);
  ALTER TABLE "MMS"."MEDICINE" MODIFY ("MEDICINE_DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "MMS"."MEDICINE" MODIFY ("MEDICINE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REQUESTRESPONSETRIGGERTABLE
--------------------------------------------------------

  ALTER TABLE "MMS"."REQUESTRESPONSETRIGGERTABLE" ADD CONSTRAINT "REQUESTRESPONSETRIGGERTABL_PK" PRIMARY KEY ("SRNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MMS"."REQUESTRESPONSETRIGGERTABLE" MODIFY ("SRNO" NOT NULL ENABLE);
  ALTER TABLE "MMS"."REQUESTRESPONSETRIGGERTABLE" MODIFY ("APPROVED" NOT NULL ENABLE);
  ALTER TABLE "MMS"."REQUESTRESPONSETRIGGERTABLE" MODIFY ("PENDING" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger REQUESTTRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MMS"."REQUESTTRIGGER" 
AFTER INSERT OR UPDATE OF ADMIN_RESPONSE,REQUEST_ID ON BRANCH_ADMIN_REQUEST 
BEGIN
  update REQUESTRESPONSETRIGGERTABLE set APPROVED=(SELECT COUNT(REQUEST_ID) FROM BRANCH_ADMIN_REQUEST WHERE BRANCH_ADMIN_REQUEST.ADMIN_RESPONSE='A')WHERE SRNO=1 ;
  update REQUESTRESPONSETRIGGERTABLE set PENDING=(SELECT COUNT(REQUEST_ID) FROM BRANCH_ADMIN_REQUEST WHERE BRANCH_ADMIN_REQUEST.ADMIN_RESPONSE='P')WHERE SRNO=1 ;

END;
/
ALTER TRIGGER "MMS"."REQUESTTRIGGER" ENABLE;
